name: Build and Deploy
on: 
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    timeout-minutes: 20
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: vuepress-deploy
      uses: PentaTea/vuepress-deploy@master
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        # TARGET_REPO: username/repo
        TARGET_BRANCH: master
        TARGET_LINK: https://TZNslVKsMb:${{ secrets.CODING_TOKEN }}@b-tree.coding.net/b-tree/B-Tree.Studio.git
        BUILD_SCRIPT: yarn && yarn docs:build && git config --global sendpack.sideband false
        BUILD_DIR: docs/.vuepress/dist/
